#  Configuration file for ActiveCraft-Core
#  Made by CPlaiz and Silencio

# Ingame Visual formats
chat-format: '%displayname%§f: %message%'
join-format: "§b» §f%displayname%"
quit-format: "§c« §f%displayname%"
# For further message customization see "messages.yml"

# Misc settings
use-timer-on-tpa: true
mute-new-players: false
remove-default-mute-after: 10 #in minutes | 0 to disable
check-for-matching-ips: true
socialspy-to-console: false
language: 'en'
announce-afk: true

# Vanish settings
enable-vanish-format: true
vanish-format: '[V]'

# Lockdown Settings
lockdown-modt: "This server is in lockdown mode. You are not able to join until this is disabled."
lockdown-kick-message: "This server is in lockdown mode. You are not able to join until this is disabled."

# Clear In Tab Complete
hide-commands-after-plugin-name: # remove commands from tab complete which have the following format: "pluginname:command"
  enable: true
  except:
    - 'minecraft:enchant'
hide-commands: # remove normal commands from tab complete
  - 'command'

# Do not edit!
lockdown:
old-modt: