#  Configuration file for ActiveCraft-Core
#  Made by CPlaiz and Silencio

# Ingame Visual formats
chat-format: '%displayname%§f: %message%'
join-format: "§b» §f%displayname%"
quit-format: "§c« §f%displayname%"

# Teleportation Timers
use-timer-on-tpa: true
use-timer-on-spawn: true
use-timer-on-home: true
use-timer-on-warp: true

# Default Mute
# When activated, players who join for the first time cannot speak in chat.
mute-new-players: false
# Set the time a new player should be muted for.
remove-default-mute-after: 10 #in minutes | 0 to disable

# Vanish Settings
# Set if the vanish tag should be shown behind player names in tab.
enable-vanish-format: true
# The tag that is shown behind player names in tab, assuming 'enable-vanish-format' is true.
vanish-format: '[V]'

# AFK Settings
# If players enabling / disabling afk mode should be broadcasted in chat.
announce-afk: true
# The tag that is shown behind player names in tab.
afk-format: '[AFK]'

# Lockdown Settings
# The server modt (Multiplayer Menu) when lockdown is activated.
lockdown-modt: "This server is in lockdown mode. You are not able to join until this is disabled."
# The kick message when players attempt to join during lockdown mode.
lockdown-kick-message: "This server is in lockdown mode. You are not able to join until this is disabled."

# Misc Settings
# If people with the permission 'activecraft.matchingip.notify' should recieve messages when a player logs in with an already known IP address.
check-for-matching-ips: true
# If player to player messages should be broadcasted to the server console.
socialspy-to-console: false
# If command targets should recieve messages in chat when someone executes a command targetted at them (I.E. /feed -> >You were fed by %displayname%).
silent-mode: false
# If players should drop all, not some, EXP on death.
drop-all-exp-on-death: true

# Clear Tab Completer
# remove commands from tab complete which have the following format: "pluginname:command"
hide-commands-after-plugin-name:
  # If this setting should be enabled.
  enable: true
  # All commands that should not be removed from the tab complete.
  except:
    - 'minecraft:enchant'
# Remove any command from tab complete.
hide-commands:
  - 'command'

# Do not edit!
lockdown:
old-modt:
language: 'en'