name: ActiveCraft-Core
version: ${project.version}
main: de.silencio.activecraftcore.Main
api-version: 1.17
authors: [ CPlaiz, Silencio ]
description: The heart of all ActiveCraft Plugins

commands:
  heal:
    description: Heals the target player.
    usage:
    permission: activecraft.heal
  spawn:
    description: Teleports you to spawn.
    aliases: ["setspawn"]
    usage: /spawn | /setspawn
  ping:
    description: Pong!
  broadcast:
    description: Server-wide broadcast.
    aliases:
      - "broadcastworld"
      - "bc"
  msg:
    description: Private message to another Player.
  invsee:
    description: Opens the targets Inventory.
  vanish:
    description: become invisible for other players.
    aliases: ["v"]
  creative:
    description: the targets gamemode to Creative.
    aliases: ["cr"]
  survival:
    description: Sets the targets gamemode to Survival.
    aliases: [ "su" ]
  spectator:
    description: Sets the targets gamemode to Spectator.
    aliases: ["sp"]
  adventure:
    description: Sets the targets gamemode to Adventure.
    aliases: ["ad"]
  clearinventory:
    description: Clears the targets inventory.
    aliases: ["clear"]
  feed:
    description: Feeds the player
  craftingtable:
    description: Opens a workbench menu.
  anvil:
    description: Opens an anvil menu.
  enchanttable:
    description: Opens an enchantment table menu.
  cartographytable:
    description: Opens a cartography table menu.
  grindstone:
    description: Opens a grindstone menu.
  loom:
    description: Opens a loom menu.
  smithingtable:
    description: Opens a smithing table menu.
  stonecutter:
    description: Opens a stonecutter menu.
  playtime:
    description: Shows a players playtime.
  repair:
    description: Repairs selected item.
  colornick:
    description: Allows the player to only change displaycolor.
  fly:
    description: Allows the player to toggle their or an other player's flight.
    aliases:
      - "flyspeed"
  offinvsee:
    description: Shows a players armor and offhand-item.
  realname:
    description: Shows a players real name.
  nick:
    description: Allows a player to change their or another players Displayname.
  god:
    description: Toggle invincibility for you or another player.
  enderchest:
    description: Opens your or another players enderchest.
    aliases: ["ec"]
  tpa:
    description: Sends a teleport request to another player.
  tpaccept:
    description: Accept a teleport request
  tpadeny:
    description: Denies a teleport request
  warp:
    description: Warp System.
    aliases:
      - "setwarp"
      - "delwarp"
      - "warps"
  home:
    description: Teleports to your home.
  sethome:
    description: Creates your home.
  delhome:
    description: Deletes your home.
  suicide:
    description: kill yourself.
  tphere:
    description: Teleports another player to you.
  opitems:
    description: Gives a player OP items.
  kickall:
    description: Kicks all players.
  ram:
    description: Shows RAM info.
  staffchat:
    description: Send a message that only other staff can see.
    aliases: ["sc"]
  reply:
    description: Sends a private message to the last player who messaged you.
    aliases: [ "r" ]
  portal:
    description: Creates or destroys a portal.
  lastonline:
    description: Gets the last time a player was online.
  whois:
    description: Gets additional infomation on a player.
  i:
    description: Gives the selected Item to the player.
  item:
    description: Multiple item operations.
  butcher:
    description: Kills all mobs.
  ban:
    description: Ban/Unban a player/ip.
    aliases:
      - "unban"
      - "ban-ip"
      - "unban-ip"
      - "banlist"
  whereami:
    description: Locates the player.
  weather:
    description: Changes weather in the players current world.
  more:
    description: Fills an Itemstack to its max stack size.
  restart-server:
    description: Restarts the server with a warning.
  mute:
    description: Mutes / unmutes a player.
    aliases:
      - "unmute"
  hat:
    description: Changes item in helmet slot.
  log:
    description: Logs all commands executed on the server.
  skull:
    description: Gives the player its own head.
  strike:
    description: Strikes a player with lightning.
  break:
    description: Breaks the targeted block.
  firework:
    description: Summons a firework.
    aliases:
      - "fw"
  book:
    description: Options to edit already signed books.
  xp:
    description: Adds xp or levels to a player.
  enchant:
    description: Enchants an item.
  lockdown:
    description: Full lockdown of the server, prohibits normal players from joining.
    aliases:
      - "lockdownbypass"
  afk:
    description: Allows a player to change AFK status.
  top:
    description: Teleports the player ontop of the highest block at the player's x/z coordinates.
  explode:
    description: Creates a explosion at a player's position.
  warn:
    description: Sends a warning to a player.
  known-ips:
    description: Gets all ips a player has logged in with.
  profile:
    description: Opens a profile inventory for quick player management.
  lastcoords:
    description: Get a player's last coords
  verify:
    description: Verifies a player.
  tpall:
    description: Teleports all players.

permissions:
  activecraft.heal:
    description: Heals the target player.
    default: op
  activecraft.heal.others:
    description: Heals other players.
    default: op
  activecraft.ping:
    description: Pong!
    default: op
  activecraft.msg:
    description: Private message to another player.
    default: op
  activecraft.msg.spy:
    description: Spy on other private messages.
    default: op
  activecraft.broadcast:
    description: Server-wide message.
    default: op
  activecraft.clearinv:
    description: Clears the targets inventory.
    default: op
  activecraft.invsee:
    description: Opens another players inventory.
    default: op
  activecraft.spawn:
    description: Allows the player to teleport to spawn.
    default: op
  activecraft.setspawn:
    description: Sets the spawn.
    default: op
  activecraft.vanish:
    description: Permission to set vanish for a player.
    default: op
  activecraft.vanish.others:
    description: Permission to set vanish for other players.
    default: op
  activecraft.vanish.see:
    description: Allows a player to see vanished players.
    default: op
  activecraft.gamemode.creative:
    description: Sets the targets gamemode to Creative.
    default: op
  activecraft.gamemode.survival:
    description: Sets the targets gamemode to Survival.
    default: op
  activecraft.gamemode.spectator:
    description: Sets the targets gamemode to Spectator.
    default: op
  activecraft.gamemode.adventure:
    description: Sets the targets gamemode to Adventure.
    default: op
  activecraft.feed:
    description: Feeds the player
    default: op
  activecraft.feed.others:
    description: Feeds other players.
    default: op
  activecraft.workbench:
    description: Opens a workbench menu.
    default: op
  activecraft.anvil:
    description: Opens an anvil menu.
    default: op
  activecraft.enchanttable:
    description: Opens an enchantment table menu.
    default: op
  activecraft.cartographytable:
    description: Opens a cartography table menu.
    default: op
  activecraft.grindstone:
    description: Opens a grindstone menu.
    default: op
  activecraft.loom:
    description: Opens a loom menu.
    default: op
  activecraft.smithingtable:
    description: Opens a smithing table menu.
    default: op
  activecraft.stonecutter:
    description: Opens a stonecutter menu.
    default: op
  activecraft.playtime:
    description: Shows a players playtime.
    default: op
  activecraft.repair:
    description: Repairs selected item.
    default: op
  activecraft.nick.color:
    description: Allows the player to only change displaycolor.
    default: op
  activecraft.fly:
    description: Allows the player to toggle their flight.
    default: op
  activecraft.fly.others:
    description: Allows the player to toggle other player's flight.
    default: op
  activecraft.flyspeed:
    description: Allows the player to change their speed while in flight.
    default: op
  activecraft.flyspeed.others:
    description: Allows the player to change other players speed while in flight.
    default: op
  activecraft.realname:
    description: Shows a players real name.
    default: op
  activecraft.nick:
    description: Allows a player to change their Displayname.
    default: op
  activecraft.nick.others:
    description: Allows a player to change another players Displayname.
    default: op
  activecraft.god:
    description: Toggle invincibility for you.
    default: op
  activecraft.god.others:
    description: Toggle invincibility for another player.
    default: op
  activecraft.enderchest:
    description: Opens your enderchest.
    default: op
  activecraft.enderchest.others:
    description: Opens another players enderchest.
    default: op
  activecraft.tpa:
    description: Sends a teleport request to another player.
    default: op
  activecraft.tpaccept:
    description: Accepts a teleport request.
    default: op
  activecraft.tpadeny:
    description: Denies a teleport request.
    default: op
  activecraft.setwarp:
    description: Permission to set a new warp.
    default: op
  activecraft.deletewarp:
    description: Permission to delete a warp.
    default: op
  activecraft.listwarps:
    description: Permission to list all warps.
    default: op
  activecraft.warp:
    description: Permission to use /warp
    default: op  
  activecraft.home:
    description: Teleports to your home.
    default: op
  activecraft.sethome:
    description: Creates your home.
    default: op
  activecraft.delhome:
    description: Deletes your home.
    default: op
  activecraft.home.others:
    description: Teleports to another players home
    default: op
  activecraft.sethome.others:
    description: Sets another players home.
    default: op
  activecraft.delhome.others:
    description: Deletes another players home.
    default: op
  activecraft.suicide:
    description: Kills you.
    default: op
  activecraft.tphere:
    description: Teleports another player to you.
    default: op
  activecraft.tp.others:
    description: Permission to teleport other players.
    default: op
  activecraft.tp:
    description: Permission to teleport.
    default: op
  activecraft.opitems:
    description: Gives a player OP items.
    default: op
  activecraft.kickall:
    description: Kicks all players.
    default: op
  activecraft.kickall.bypass:
    description: Prevents a player from being kicked by /kickall.
    default: op
  activecraf.ram:
    description: Shows RAM info.
    default: op
  activecraft.staffchat:
    description: Send a message that only other staff can see.
    default: op
  activecraft.reply:
    description: Sends a private message to the last player who messaged you.
    default: op
  activecraft.portal.create:
    description: Permission to create a portal.
    default: op
  activecraft.portal.destroy:
    description: Permission to destroy a portal.
    default: op
  activecraft.portal.list:
    description: Permission to list all portals.
    default: op
  activecraft.lastonline:
    description: Permission to get the last time a player was online.
    default: op
  activecraft.whois:
    description: Permission to get infomation on a player.
    default: op
  activecraft.quickgive:
    description: Gives the selected Item to the player.
    default: op
  activecraft.butcher:
    description: Kills all mobs.
    default: op
  activecraft.kill:
    description: Permission to kill players.
    default: op
  activecraft.item.give:
    description: Permission to give items to players.
    default: op
  activecraft.item.name:
    description: Permission to rename items.
    default: op
  activecraft.item.lore:
    description: Permission to change the lore of an item.
    default: op
  activecraft.item.tag:
    description: Permission to change the tag of an item.
    default: op
  activecraft.whereami:
    description: Locates the player.
    default: op
  activecraft.whereami.others:
    description: Locates other players.
    default: op
  activecraft.weather:
    description: Changes weather in the players current world.
    default: op
  activecraft.more:
    description: Fills an Itemstack to its max stack size.
    default: op
  activecraft.restart:
    description: Restarts the server with a warning.
    default: op
  activecraft.mute:
    description: Mutes / unmutes a player.
    default: op
  activecraft.muted.see:
    description: Allows admins to see messages from muted players.
    default: op
  activecraft.hat:
    description: Changes item in helmet slot.
    default: op
  activecraft.log:
    description: Logs all commands executed on the server.
    default: op
  activecraft.skull:
    description: Gives the player its own head.
    default: op
  activecraft.skull.others:
    description: Gives the player another players head.
    default: op
  activecraft.strike:
    description: Strikes a player with lightning.
    default: op
  activecraft.break:
    description: Breaks the targeted block.
    default: op
  activecraft.firework:
    description: Summons a firework.
    default: op
  activecraft.book:
    description: Options to edit already signed books.
    default: op
  activecraft.xp:
    description: Adds xp or levels to a player.
    default: op
  activecraft.xp.others:
    description: Adds xp or levels to another player.
    default: op
  activecraft.enchant:
    description: Enchants an item.
    default: op
  activecraft.lockdown:
    description: Full lockdown of the server, prohibits normal players from joining.
    default: op
  activecraft.lockdown.bypass:
    description: Allows a player to join the server even in lockdown mode.
    default: op
  activecraft.lockdown.allowbypass:
    description: Allows ingame players to change lockdown bypass settings temporarily.
    default: op
  activecraft.afk:
    description: Allows a player to change their AFK status
    default: op
  activecraft.afk.others:
    description: Allows a player to change AFK status for other players.
    default: op
  activecraft.matchingip.notify:
    description: Player with this permissions get a message if somebody's ip matches another.
    default: op
  activecraft.top:
    description: Teleports the player ontop of the highest block at the player's x/z coordinates.
    default: op
  activecraft.explode:
    description: Creates a explosion at the player's position.
  activecraft.explode.other:
    description: Creates a explosion at a player's position.
    default: op
  activecraft.warn.add:
    description: Allows a player to add a warning.
    default: op
  activecraft.warn.remove:
    description: Allows a player to remove a warning.
    default: op
  activecraft.warn.get:
    description: Allows a player to list all warnings.
    default: op
  activecraft.listips:
    description: Gets all ips a player has logged in with.
  activecraft.profile:
    description: Opens a profile inventory for quick player management.
    default: op
  activecraft.lastcoords:
    description: Gets the last coords of a player in a give world.
    default: op
  activecraft.verify:
    description: Verifies a player.
    default: op
  activecraft.ban:
    description: Permission to ban/ip-ban/unban/ip-unban a player and perform /banlist.
    default: op
  activecraft.location:
    description: Permission to see player locations.
    default: op
  activecraft.activeeffects:
    description: Permission to see active effects on players.
    default: op
  activecraft.kick:
    description: Permission to kick players from the server.
    default: op
  activecraft.tpall:
    description: Permission to teleport all players.
    default: op
  activecraft.tpall.exept:
    description: Prevents the holder from being teleported will /tpall.
    default: op